authentication/urls.py
from django.urls import path

from .views import *

app_name = 'authentication'

urlpatterns = [
    path('authentication/login/', login_page, name='login-view'),
    path('authentication/logout/', logout_page, name='logout-view'),
    path('authentication/register/', register_page, name='register-view'),
]

quiz/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quizes.urls', namespace='quizes')),
    path('', include('authentication.urls', namespace='authentication')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

authentication/models.py
from django.db import models

authentication/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1','password2']

authentication/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import redirect, render

from .forms import MyUserCreationForm


def register_page(request):

    if request.user.is_authenticated:
        return redirect('/')

    form = MyUserCreationForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            return redirect("/")

    return render(request, 'authentication/register.html', {'form':form})

def login_page(request):
    
    if request.user.is_authenticated:
        return redirect('/')

    form = AuthenticationForm()
    if request.method == "POST":
        username = request.POST.get("username")
        password =  request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("/")

        else:
            return redirect("authentication:login-view")
            
    context = {'form':form} 
    return render(request, "authentication/login.html", context)

def logout_page(request):
    logout(request)
    return redirect('authentication:login-view')

authentication/templates/authentication/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Login
{% endblock title %}

{% block content %}
<div class="d-flex justify-content-center">
    <form class="center-block" method="POST">
        {% csrf_token %}
        
        <h2>Login</h2>

        <div>
            {{form.as_p}}
        </div>
        
        <input class="button mt-3" type='submit' value='Login'>
    </form>
    <p>Don't have an account yet? <a href="{% url 'authentication:register-view'%}">Register</a></p>
</div>
{% endblock content %}

authentication/templates/authentication/register.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Register
{% endblock title %}

{% block content %}
    <div class="d-flex justify-content-center">
        <form class="center-block" method="POST">
            {% csrf_token %}
            <h2>Register</h2>
            <div>
                <label class="pt-3 mr-3">{{form.email.label}}:</label>
                {{form.email}}
            </div>
            <div>
                <label class="mr-3">{{form.username.label}}:</label>
                {{form.username}}
            </div>
            <div>
                <label class="mr-3">{{form.password1.label}}:</label>
                {{form.password1}}
            </div>
            <div>
                <label class="mr-3">{{form.password2.label}}:</label>
                {{form.password2}}
            </div>
            <input class="button mt-3" type='submit' value='Register'>
        </form>
        <p>Already have an account? <a href="{% url 'authentication:login-view'%}">Login</a></p>
    </div>
{% endblock content %}