quiz/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quizes.urls', namespace='quizes')),
    path('', include('authentication.urls', namespace='authentication')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quizes/urls.py
from django.urls import path

from .views import (AnswerCreateView, QuizCreateView, QuizDeleteView,
                    QuizListView, logout_view, question_create_view,
                    quiz_data_view, quiz_view, save_quiz_view)

app_name = 'quizes'

urlpatterns = [
    path('', QuizListView.as_view(), name='main-view'),
    path('logout', logout_view, name='logout-view'),
    path('createquiz/', QuizCreateView.as_view(), name='quiz-create-view'),
    path('<pk>/createquestion/', question_create_view, name='question-create-view'),
    path('createanswer/', AnswerCreateView.as_view(), name='answer-create-view'),
    path('<pk>/', quiz_view, name="quiz-view"),
    path('<pk>/delete', QuizDeleteView.as_view(), name="quiz-delete-view"),
    path('<pk>/save', save_quiz_view, name="save-view"),
    path('<pk>/data', quiz_data_view, name="quiz-data-view"),
]

quizes/models.py
import random

from django.core.validators import MaxValueValidator
from django.db import models

DIFF_CHOICES = (
    ("easy", "easy"),
    ("medium", "medium"),
    ("hard", "hard")
)


class Quiz(models.Model):
    name = models.CharField(max_length=120)
    topic = models.CharField(max_length=120)
    number_of_questions = models.IntegerField()
    time = models.IntegerField(help_text="(duration of the quiz in minutes)")
    required_score_to_pass = models.IntegerField(help_text="(required score in %, 100 limit)", validators=[MaxValueValidator(100)])
    difficulty = models.CharField(max_length=6, choices=DIFF_CHOICES)

    def __str__(self):
        return f"{self.name}"
    
    def get_questions(self):
        questions = list(self.question_set.all())
        random.shuffle(questions)
        return questions[:self.number_of_questions]

    class Meta:
        verbose_name_plural = "Quizes"

quizes/forms.py
from django.forms import ModelForm
from questions.models import Answer, Question

from .models import Quiz


class QuizForm(ModelForm):
    class Meta:
        model = Quiz
        fields = ['name', 'topic', 'number_of_questions', 'time', 'required_score_to_pass', 'difficulty']

class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = ['text']

class AnswerForm(ModelForm):
    class Meta:
        model = Answer
        fields = ['text', 'correct', 'question']

quizes/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.views.generic import CreateView, ListView
from django.views.generic.edit import DeleteView
from questions.models import Answer, Question
from results.models import Result

from quizes.forms import QuestionForm, QuizForm

from .models import Quiz


class QuizListView(LoginRequiredMixin, ListView):
    model = Quiz
    template_name = 'quizes/main.html'
    login_url = 'authentication/login'
    redirect_field_name = ''
    form_class = QuizForm

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            request.session['errorQuiz'] = False
            return redirect('/')
        else:
            request.session['errorQuiz'] = True
            return redirect('/')

    def get_context_data(self, **kwargs):          
        context = super().get_context_data(**kwargs)                     
        quiz_count = Quiz.objects.all().count()
        context["quiz_count"] = quiz_count
        return context

class QuizCreateView(LoginRequiredMixin, CreateView):
    model = Quiz
    template_name = 'quizes/quiz_modal_form.html'
    fields = [
        'name', 
        'topic', 
        'number_of_questions', 
        'time', 
        'required_score_to_pass', 
        'difficulty'
    ]
    success_url = '/'

def question_create_view(request, pk):
    q = Quiz.objects.get(pk=pk)
    form = QuestionForm(request.POST)

    if request.method == 'POST':
        if form.is_valid():
            form = form.save(commit=False)
            form.quiz = q
            form.save()
            form = QuestionForm()
            return redirect('/')
    form = QuestionForm()
    return render(request, 'quizes/question_modal_form.html', {'form':form})

class AnswerCreateView(LoginRequiredMixin, CreateView):
    model = Answer
    template_name = 'quizes/answer_modal_form.html'
    fields = [
        'text', 
        'correct', 
        'question'
    ]
    success_url = '/'


class QuizDeleteView(LoginRequiredMixin, DeleteView):
    model = Quiz
    success_url = '/'
    
@login_required(login_url="authentication:login-view")
def quiz_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    return render(request, 'quizes/quiz.html', {'obj':quiz})

@login_required(login_url="authentication:login-view")
def quiz_data_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    questions = []
    for q in quiz.get_questions():
        answers = []
        for a in q.get_answers():
            answers.append(a.text)
        questions.append({str(q): answers})
    return JsonResponse({
        'data':questions,
        'time':quiz.time
    })

@login_required(login_url="authentication:login-view")
def save_quiz_view(request, pk):
    is_ajax = request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'
    if is_ajax:
        questions = []
        data = request.POST
        data_ = dict(data.lists())

        data_.pop('csrfmiddlewaretoken')

        for k in data_.keys():
            question = Question.objects.get(text=k)
            questions.append(question)

        user = request.user
        quiz = Quiz.objects.get(pk=pk)

        score = 0
        multiplier = 100 / quiz.number_of_questions
        results = []
        correct_answer = None

        for q in questions:
            a_selected = request.POST.get(q.text)

            if a_selected != "":
                question_answers = Answer.objects.filter(question=q)
                for a in question_answers:
                    if a_selected == a.text:
                        if a.correct:
                            score += 1
                            correct_answer = a.text
                    else:
                        if a.correct:
                            correct_answer = a.text

                results.append({str(q): {'correct_answer': correct_answer, 'answered': a_selected}})
            else:
                results.append({str(q): 'not answered'})
            
        score_ = score * multiplier
        Result.objects.create(quiz=quiz, user=user, score=score_)

        if score_ >= quiz.required_score_to_pass:
            return JsonResponse({'passed': True, 'score': score_, 'results': results})
        else:
            return JsonResponse({'passed': False, 'score': score_, 'results': results})

def logout_view(request):
    return render(request, 'quizes/logout_confirm.html')

quizes/templates/quizes/answer_modal_form.html
{% extends 'base.html' %}
{% block title %}
Add a new Answer
{% endblock title %}

{% block content %}
<h2 class='modal-title'>Create a new Answer</h2>
<form action='' method='POST'> 
    {% csrf_token %}
    {{ form.as_p }}
    <input class='btn btn-danger' type='button' onclick="window.history.go(-1);" value="Cancel"></input>
    <input class='btn btn-primary' type='submit'></input>
</form>
{% endblock content %}

quizes/templates/quizes/logout_confirm.html
{% extends "base.html" %}

{% block title %} Logout {% endblock title%}

{% block content %}
<h1>Logout</h1>

<p>Are you sure you want to sign out?</p>

<form method="post" action="{% url 'authentication:logout-view' %}">
  {% csrf_token %}
  <input type="button" value="Cancel" 
         onclick="window.history.go(-1);"/>
  <button type="submit">Sign Out</button>
</form>
{% endblock %}

quizes/templates/quizes/main.html
{% extends 'base.html' %}
{% load static %}

{% block scripts %}
    <script src="{% static 'quizes/main.js' %}" defer></script>
    <script type="text/javascript">
        function customModalFunction(url){
            $('#customModal').load(url, function(){
                $(this).modal('show');
            })
        }
    </script>
{% endblock scripts %}

{% block title %}
    Home
{% endblock title %}

{% block content %}

<!-- Basic Info -->
<div class="justify-content-center">
    {% if request.session.errorQuiz %}
    <div class="alert alert-danger" role="alert">
        Quiz filled incorrectly. Please try again.  
    </div>
    {% endif %}
    Quizes Available: {{quiz_count}}
    <a href="{% url 'quizes:logout-view' %}"  class="btn btn-dark btn-lg mb-1 float-right">
        Logout
    </a>
    <button onclick="customModalFunction('{% url 'quizes:quiz-create-view' %}')"  class="btn btn-info btn-lg mr-4 float-right">
        Create a Quiz
    </button>
    <div>
        <h1>Quizes:</h1>
    </div>
</div>
<hr>


<!-- Quizes -->
{% for obj in object_list %}
<h5>#{{forloop.counter}}</h5>
<h4>{{obj.name}}</h4>
<button 
    class="btn btn-success modal-button"
    data-pk="{{obj.pk}}"
    data-quiz="{{obj.name}}"
    data-questions="{{obj.number_of_questions}}"
    data-difficulty="{{obj.difficulty}}"
    data-time="{{obj.time}}"
    data-pass="{{obj.required_score_to_pass}}"
    data-toggle="modal" 
    data-target="#quizStartModal">
    Click to see more info
</button>
<a href="{% url 'quizes:quiz-delete-view' obj.pk %}" id="my_delete_button" class="btn btn-danger btn-sm mb-1 float-right">
    Delete Quiz
</a>
<a href="{% url 'quizes:answer-create-view' %}" class="btn btn-secondary btn-sm mr-4 float-right">
    Add Answers
</a>
<a href="{% url 'quizes:question-create-view' obj.pk %}" class="btn btn-primary btn-sm mr-4 float-right">
    Add Questions
</a>
<br>
<hr>

{% endfor %}


<!-- Load Modal from Other Templates -->
<div class="modal fade" id="customModal" role="dialog">
</div>

<!-- Quiz Info Modal -->
<div class="modal fade" id="quizStartModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Test Details</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </div>
        <div class="modal-body" id="modal-body-confirm"></div>
        <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            <button type="button" id="start-button" class="btn btn-success">Start the Test</button>
        </div>
        </div>
    </div>
</div>



{% endblock content %}

quizes/templates/quizes/question_modal_form.html
{% extends 'base.html' %}
{% block title %}
Add a new Question
{% endblock title %}

{% block content %}
<h2 class='modal-title'>Create a new Question</h2>
<form action='' method='POST'> 
    {% csrf_token %}
    {{ form.as_p }}
    <input class='btn btn-link' type='button' onclick="window.history.go(-1);" value="Cancel"></input>
    <input class='btn btn-primary' type='submit'></input>
</form>
{% endblock content %}

quizes/templates/quizes/quiz.html
{% extends 'base.html' %}
{% load static %}

{% block scripts %}
    <script src="{% static 'quizes/quiz.js' %}" defer></script>
{% endblock scripts %}

{% block title %}
    {{obj.name}}
{% endblock title %}

{% block content %}
<div class="row">
    <div class="col">
        <b>{{obj.name}}</b>
        <p>Score to Pass: {{obj.required_score_to_pass}}%</p>
    </div>
    <div class="col text-right" id='timer-box'></div>
</div>

<a href="{% url 'quizes:main-view' %}" class="btn btn-danger">Go Back</a>

<hr>

<form id="quiz-form" class="mt-3 mb-3">
    {% csrf_token %}
    <div id="quiz-box"></div>
    <button type="submit" class="btn btn-primary mt-3">Save</button>
</form>
<div id="score-box"></div>
<div id="result-box"></div>
{% endblock content %}

quizes/templates/quizes/quiz_confirm_delete.html
{% extends 'base.html' %}
{% block title %}
Delete Quiz
{% endblock title %}

{% block content %}
    <div id="content-container" class="container p-none">
        <div class="side-p">
            <h3>Are you sure?</h3>
            <p>You're about to delete "{{ object }}". Please confirm.</p>
            <form action="" method="post">
                {% csrf_token %}
                <input class="btn btn-link" 
                       type="button" value="Cancel" 
                       onclick="window.history.go(-1);"/>
                <input class="btn btn-danger" type="submit" value="Confirm"/>
            </form>
        </div>
    </div>
{% endblock content %}

quizes/templates/quizes/quiz_modal_form.html
<div class='modal-dialog modal-lg' role='dcoument'>
    <div class='modal-content'>
        <div class='modal-header'>
            <h2 class='modal-title'>Create a new Quiz</h2>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <form action='' method='POST'> 
            {% csrf_token %}
            <div class='modal-body'>
                {{ form.as_p }}
            </div>
            <div class='modal-footer'>
                <button class='btn btn-danger' type='button' data-dismiss='modal'>Cancel</button>
                <button class='btn btn-primary' type='submit'>Submit</button>
            </div>
        </form>
    </div>
</div>